get_shmem.out : get_shmem.c
	gcc get_shmem.c -o get_shmem.out

data_seg_end.out : data_seg_end.c
	gcc data_seg_end.c -o data_seg_end.out

attach_shmem.out : attach_shmem.c
	gcc attach_shmem.c -o attach_shmem.out

fork_change_stack.out : fork_change_stack.c
	gcc fork_change_stack.c -o fork_change_stack.out

write_shmem.out : write_shmem.c
	gcc write_shmem.c -o write_shmem.out
