get_max_priority.out : get_max_priority.c
	gcc get_max_priority.c -o get_max_priority.out

set_affinity.out : set_affinity.c
	gcc set_affinity.c -o set_affinity.out

procinfo.out : procinfo.c
	gcc procinfo.c -o procinfo.out
